package com.bakeease.views;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author piyushkarn
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
    }

    // Create an ArrayList to store product data
    ArrayList<String> productList = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminBackground = new javax.swing.JPanel();
        lblEnterDetails = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        lblAdminText = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtFldProductName = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtFldQuantity = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtFldPrice = new javax.swing.JTextField();
        txtFldWeight = new javax.swing.JTextField();
        lblWeight = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnDeleteRowRecord = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblAdminTable = new javax.swing.JLabel();
        scrollPaneTable = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        lblAdminBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 900));
        getContentPane().setLayout(null);

        pnlAdminBackground.setMaximumSize(new java.awt.Dimension(1400, 900));
        pnlAdminBackground.setMinimumSize(new java.awt.Dimension(1400, 900));
        pnlAdminBackground.setSize(new java.awt.Dimension(1400, 900));
        pnlAdminBackground.setLayout(null);

        lblEnterDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblEnterDetails.setText("Enter Details");
        pnlAdminBackground.add(lblEnterDetails);
        lblEnterDetails.setBounds(140, 210, 240, 40);

        btnReturn.setBackground(new java.awt.Color(255, 51, 51));
        btnReturn.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/return icon.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        pnlAdminBackground.add(btnReturn);
        btnReturn.setBounds(10, 10, 80, 56);

        lblAdminText.setFont(new java.awt.Font("Helvetica Neue", 2, 48)); // NOI18N
        lblAdminText.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminText.setText("Admin");
        pnlAdminBackground.add(lblAdminText);
        lblAdminText.setBounds(1180, 30, 140, 50);

        lblProductName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProductName.setText("Enter Product Name:");
        pnlAdminBackground.add(lblProductName);
        lblProductName.setBounds(30, 300, 180, 40);

        txtFldProductName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtFldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldProductNameActionPerformed(evt);
            }
        });
        pnlAdminBackground.add(txtFldProductName);
        txtFldProductName.setBounds(260, 300, 210, 40);

        lblQuantity.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblQuantity.setText("Enter Quantity:");
        pnlAdminBackground.add(lblQuantity);
        lblQuantity.setBounds(30, 380, 180, 40);

        txtFldQuantity.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pnlAdminBackground.add(txtFldQuantity);
        txtFldQuantity.setBounds(260, 380, 210, 40);

        lblPrice.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblPrice.setText("Enter price:");
        pnlAdminBackground.add(lblPrice);
        lblPrice.setBounds(30, 450, 180, 40);

        txtFldPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pnlAdminBackground.add(txtFldPrice);
        txtFldPrice.setBounds(260, 450, 210, 40);

        txtFldWeight.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pnlAdminBackground.add(txtFldWeight);
        txtFldWeight.setBounds(260, 520, 210, 40);

        lblWeight.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWeight.setText("Enter product weight:");
        pnlAdminBackground.add(lblWeight);
        lblWeight.setBounds(30, 530, 190, 20);

        btnSubmit.setBackground(new java.awt.Color(102, 255, 102));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlAdminBackground.add(btnSubmit);
        btnSubmit.setBounds(130, 600, 130, 50);

        btnDeleteRowRecord.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteRowRecord.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnDeleteRowRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteRowRecord.setText("Delete records");
        btnDeleteRowRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRowRecordActionPerformed(evt);
            }
        });
        pnlAdminBackground.add(btnDeleteRowRecord);
        btnDeleteRowRecord.setBounds(930, 600, 170, 50);

        btnClear.setBackground(new java.awt.Color(255, 102, 102));
        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlAdminBackground.add(btnClear);
        btnClear.setBounds(290, 600, 130, 50);

        lblAdminTable.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblAdminTable.setText("Admin Table");
        pnlAdminBackground.add(lblAdminTable);
        lblAdminTable.setBounds(930, 180, 230, 30);

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price", "Weight"
            }
        ));
        scrollPaneTable.setViewportView(adminTable);

        pnlAdminBackground.add(scrollPaneTable);
        scrollPaneTable.setBounds(630, 250, 740, 300);

        lblAdminBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/admin.png"))); // NOI18N
        pnlAdminBackground.add(lblAdminBackground);
        lblAdminBackground.setBounds(0, 0, 1400, 900);

        getContentPane().add(pnlAdminBackground);
        pnlAdminBackground.setBounds(0, 0, 1400, 900);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        // creating object of home page
        homePage home = new homePage();
        // Set the homePage visible
        home.setVisible(true);
        // set current page visible as false
        setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    /*
    Method to add data to table.
    A part of CRUD operations.
    */
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Get input values
        String productName = txtFldProductName.getText();
        String quantityString = txtFldQuantity.getText();
        String priceString = txtFldPrice.getText();
        String weightString = txtFldWeight.getText();

        // validate empty fields
        if (productName.isEmpty() || quantityString.isEmpty() || priceString.isEmpty() || weightString.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty Fields Detected!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                // parsing the supposed strings values into integer
                int quantityInt = Integer.parseInt(quantityString);
                int price = Integer.parseInt(priceString);
                int weight = Integer.parseInt(weightString);

                // ADDING VALUES TO ARRAY LIST
                // adding product name to arrayList
                productList.add(productName);
                // adding quantity to arrayList
                productList.add(quantityString);
                // adding price to array list
                productList.add(priceString);
                // adding weight to arrayList
                productList.add(weightString);

                /* Inserting into table
                Cast the table model of adminTable to DefaultTableModel
                This allows us to directly access and manipulate the underlying data structure of the table (e.g., adding or removing rows) 
                 */
                // creating model of Table
                DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
                // adding the data into the table row
                model.addRow(new Object[]{txtFldProductName.getText(), txtFldQuantity.getText(), txtFldPrice.getText(), txtFldWeight.getText()});

                // added succesfully message
                JOptionPane.showMessageDialog(null, "Added to the table succesfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Quantity, Price and Weight must be numeric!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    // method to clear text fields
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFldProductName.setText("");
        txtFldQuantity.setText("");
        txtFldPrice.setText("");
        txtFldWeight.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    /* method to remove selected row
    A part of CRUD operations
     */
    private void btnDeleteRowRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRowRecordActionPerformed
        DefaultTableModel model = (DefaultTableModel) adminTable.getModel();
        model.removeRow(adminTable.getSelectedRow());
    }//GEN-LAST:event_btnDeleteRowRecordActionPerformed

    private void txtFldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldProductNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteRowRecord;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAdminBackground;
    private javax.swing.JLabel lblAdminTable;
    private javax.swing.JLabel lblAdminText;
    private javax.swing.JLabel lblEnterDetails;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JPanel pnlAdminBackground;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTextField txtFldPrice;
    private javax.swing.JTextField txtFldProductName;
    private javax.swing.JTextField txtFldQuantity;
    private javax.swing.JTextField txtFldWeight;
    // End of variables declaration//GEN-END:variables
}
