package com.bakeease.views;

/**
 *
 * @author piyushkarn
 */
public class ViewProductPage extends javax.swing.JFrame {

    /**
     * Creates new form viewProductPage
     */
    public ViewProductPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlViewPrdocutBackground = new javax.swing.JPanel();
        lblProductPageHeader = new javax.swing.JLabel();
        btnReturnToHome = new javax.swing.JButton();
        pnlCakeDisplay = new javax.swing.JPanel();
        lblCake1 = new javax.swing.JLabel();
        lblCake2 = new javax.swing.JLabel();
        lblCake3 = new javax.swing.JLabel();
        pnlDoughnutsDisplay = new javax.swing.JPanel();
        lblDoughnuts1 = new javax.swing.JLabel();
        lblDoughnuts2 = new javax.swing.JLabel();
        lblDoughnuts3 = new javax.swing.JLabel();
        lblBackgroundViewProducts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 900));

        pnlViewPrdocutBackground.setMaximumSize(new java.awt.Dimension(1400, 900));
        pnlViewPrdocutBackground.setMinimumSize(new java.awt.Dimension(1400, 900));
        pnlViewPrdocutBackground.setPreferredSize(new java.awt.Dimension(1400, 900));
        pnlViewPrdocutBackground.setLayout(null);

        lblProductPageHeader.setFont(new java.awt.Font("Kohinoor Bangla", 1, 48)); // NOI18N
        lblProductPageHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblProductPageHeader.setText("Prodcuts");
        pnlViewPrdocutBackground.add(lblProductPageHeader);
        lblProductPageHeader.setBounds(720, 80, 210, 50);

        btnReturnToHome.setBackground(new java.awt.Color(255, 51, 51));
        btnReturnToHome.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnReturnToHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/return icon.png"))); // NOI18N
        btnReturnToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToHomeActionPerformed(evt);
            }
        });
        pnlViewPrdocutBackground.add(btnReturnToHome);
        btnReturnToHome.setBounds(10, 790, 170, 70);

        pnlCakeDisplay.setBackground(new java.awt.Color(168, 122, 100));

        lblCake1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/chocolate cake.png"))); // NOI18N

        lblCake2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/birthday cake.png"))); // NOI18N

        lblCake3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/african cake.png"))); // NOI18N

        javax.swing.GroupLayout pnlCakeDisplayLayout = new javax.swing.GroupLayout(pnlCakeDisplay);
        pnlCakeDisplay.setLayout(pnlCakeDisplayLayout);
        pnlCakeDisplayLayout.setHorizontalGroup(
            pnlCakeDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCakeDisplayLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCake1)
                .addGap(172, 172, 172)
                .addComponent(lblCake2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(lblCake3)
                .addGap(40, 40, 40))
        );
        pnlCakeDisplayLayout.setVerticalGroup(
            pnlCakeDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCakeDisplayLayout.createSequentialGroup()
                .addComponent(lblCake2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlCakeDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCakeDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCake3)
                    .addComponent(lblCake1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlViewPrdocutBackground.add(pnlCakeDisplay);
        pnlCakeDisplay.setBounds(440, 310, 820, 150);

        pnlDoughnutsDisplay.setBackground(new java.awt.Color(168, 122, 100));

        lblDoughnuts1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/creampied doughnuts.png"))); // NOI18N

        lblDoughnuts2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/pink doughnuts.png"))); // NOI18N

        lblDoughnuts3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/products/yeast doughnuts.png"))); // NOI18N

        javax.swing.GroupLayout pnlDoughnutsDisplayLayout = new javax.swing.GroupLayout(pnlDoughnutsDisplay);
        pnlDoughnutsDisplay.setLayout(pnlDoughnutsDisplayLayout);
        pnlDoughnutsDisplayLayout.setHorizontalGroup(
            pnlDoughnutsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoughnutsDisplayLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDoughnuts1)
                .addGap(178, 178, 178)
                .addComponent(lblDoughnuts2)
                .addGap(117, 117, 117)
                .addComponent(lblDoughnuts3)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        pnlDoughnutsDisplayLayout.setVerticalGroup(
            pnlDoughnutsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoughnutsDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoughnutsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDoughnuts1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDoughnutsDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDoughnuts3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDoughnuts2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlViewPrdocutBackground.add(pnlDoughnutsDisplay);
        pnlDoughnutsDisplay.setBounds(440, 600, 820, 160);

        lblBackgroundViewProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bakeease/resource/product page.png"))); // NOI18N
        pnlViewPrdocutBackground.add(lblBackgroundViewProducts);
        lblBackgroundViewProducts.setBounds(0, -10, 1400, 920);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlViewPrdocutBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlViewPrdocutBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToHomeActionPerformed
        // creating object of home page
        HomePage home = new HomePage();
        // Set the homePage visible
        home.setVisible(true);
        // set current page visible as false
        setVisible(false);
    }//GEN-LAST:event_btnReturnToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProductPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnToHome;
    private javax.swing.JLabel lblBackgroundViewProducts;
    private javax.swing.JLabel lblCake1;
    private javax.swing.JLabel lblCake2;
    private javax.swing.JLabel lblCake3;
    private javax.swing.JLabel lblDoughnuts1;
    private javax.swing.JLabel lblDoughnuts2;
    private javax.swing.JLabel lblDoughnuts3;
    private javax.swing.JLabel lblProductPageHeader;
    private javax.swing.JPanel pnlCakeDisplay;
    private javax.swing.JPanel pnlDoughnutsDisplay;
    private javax.swing.JPanel pnlViewPrdocutBackground;
    // End of variables declaration//GEN-END:variables
}
